### ISSUE TITLE
Problem with two icons

### ISSUE THREAD

**Issue by bzhmurov** [gusbemacbe/suru-plus-telinkrin#3]
Hello,

I use Debian 9 stable (Stretch) with Gnome 3.22.3 (default Debian 9 installation with Gnome desktop).
Latest Telikrin GTK theme and latest SURU++ and SURU++ Telirkin icons.

Please take a look ar screenshot attached, I've underlined two problems:
1. Looks like icon from "disk drive" is used for a "Clock" applet
2. Wrong type of icon is used for gnome-control-center in dash-to-dock extension. The size of dash-to-dock icons is 32.

![screenshot2](https://user-images.githubusercontent.com/729083/40686511-77fc54fa-638f-11e8-9dac-e10341adca61.png)

Thanks,

**Comment by gusbemacbe** [comment]
This is the old version of Telinkrin. It is why I updated the version of Telinkrin today morning, not just purged the dead symlinks, but I am going to push it when I finish to readjust README and instructions. 

@Magog64 has fixed it. See if the latest version of Suru++ still has this same problem. 

I also noticed that Slack and Skype icons are not displayed. May I know the icons name from `Icon=...` from desktop files?

**Comment by bzhmurov** [comment]
Thank you, latest version of Suru++ icons has fixed problem with clocks.

Here are desktop files from Slack and Skypeforlinux packages. This is default desktop files from them.

`[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
`


`
[Desktop Entry]
Name=Skype
Comment=Skype Internet Telephony
Exec=/usr/share/skypeforlinux/skypeforlinux %U
Icon=skypeforlinux
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=Skype
Encoding=UTF-8
Categories=Network;Application;
MimeType=x-scheme-handler/skype;
X-KDE-Protocols=skype
Actions=QuitSkype;
`

**Comment by gusbemacbe** [comment]
The wrong icons of Clocks have been fixed by @Magog64.
