### ISSUE TITLE
Fixed and purged dead symlinks

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus-telinkrin#5]
Hello @btd1337 and @bzhmurov,

Sorry for my absence. I was busy with my college. My professors were too demanding and liked to test our patience and resistence. Now I am on holidays.

I have just released the new version, after having having purged all the dead symlinks. I redesigned and readjusted more than 1000 icons. 

I will ask @Magog64 to avoid the symlinks. 

Please, remove the old folder, if you downloaded via SVN. If you downloaded via PPA, please, remove the PPA and download the package from here without SVN. Please, tell me if they work. 

If they work for both you, I will update the AUR and the PPA. 

Gustavo Costa

**Comment by gusbemacbe** [comment]
I have tested on Debian Stretch, but they still do not work in the Gnome Centre Control, but I have tested Numix icons, interesting, they worked in the Gnome Centre Control. I will study Numix icons tomorrow.

**Comment by gusbemacbe** [comment]
@btd1337

As you are an user of Arch Linux, please install:

```
pacaur -S suru-plus-telinkrin --noconfirm

# or

yaourt -Ss suru-plus-telinkrin --noconfirm
```

**Comment by bzhmurov** [comment]
Yes, much better now, thanks! But still have wrong icon for **Clocks**, please see screenshot
![screenshot from 2018-06-24 20-21-35](https://user-images.githubusercontent.com/729083/41822787-1d138460-77ed-11e8-862e-33d6fa92b703.png)

**Comment by gusbemacbe** [comment]
Ah, Andrea failed to fix. Therefore, he is not a programmer. I have to fix by myself. 

As you are a Russian, when my icons themes will be fixed and finished, can you translate the `index.theme` into Russian, please? 

Please, get the names of missed icons of these apps: GNOME MPV, lftp and Midnight Commander (although I have already drawn it).

**Comment by Magog64** [comment]
Fixed icons Clock

**Comment by gusbemacbe** [comment]
@Magog64, ma queste icne sono risolte nel tuo repositorio Suru++ e non nel Suru++ Telinkrin, oi devo copiarle nel prossimo aggiornamento.

**Comment by bzhmurov** [comment]
> As you are a Russian, when my icons themes will be fixed and finished, can you translate the 
> index.theme into Russian, please?

I'd be happy to. I can also translate it to Ukrainian and Belarus aswell if you want. 


> Please, get the names of missed icons of these apps: GNOME MPV, lftp and Midnight Commander 

mc.desktop -> Icon=MidnightCommander
mcedit.desktop -> Icon=MidnightCommander

io.github.GnomeMpv.desktop ->  Icon=io.github.GnomeMpv

lftp.desktop -> Icon=lftp-icon

**Comment by gusbemacbe** [comment]
@bzhmurov 

Sorry for my absence. During a week I made a lot of icons. I updated, adding 381 icons, including the Debian's Gnome Control Centre. Please test my classic Suru++ and tell me if it works on Gnome Control Center. Check https://github.com/gusbemacbe/suru-plus/releases/tag/v15

If it works, I will update to Dark and Telinkrin.

**Comment by gusbemacbe** [comment]
I have just tested in Debian 9 Stretch with GNOME 3.22.2 and it was well succeeded:

![debian gnome control centre success](https://user-images.githubusercontent.com/2257024/42298571-0868819e-7fdd-11e8-81c1-8f3f02fa41c8.png)

**Comment by gusbemacbe** [comment]
@bzhmurov 

Good news! It worked finally. It were not the missed icons. It was the `index.theme` of Telinkrin which is different of Suru++'s and I have fixed it. Here is the result:

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus-telinkrin/master/pictures/gnome-control-centre.png" alt="result" class="inline"/>

**Comment by gusbemacbe** [comment]
As @bzhmurov  has confirmed, I close the issue.
